version: '2'

services:
    api:
        image: python:3.6
        working_dir: /src
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_HOST
            - POSTGRES_PORT
            - POSTGRES_POOL_MIN_CONN
            - POSTGRES_POOL_MAX_CONN
            - REDIS_HOST
            - REDIS_PORT
            - REDIS_TOKEN_DB
        volumes:
            - ./api:/src
        command: >
            bash -c "pip install pipenv && pipenv --python 3.6 &&
            pipenv install && pipenv run python app.py"
        ports:
            - '5000:5000'
        depends_on:
            - database
            - cache
        restart: unless-stopped
    frontend:
        image: node:8
        working_dir: /src
        volumes:
          - ./frontend:/src
        command: bash -c "npm install && npm run dev"
        ports:
            - '8080:8080'
        depends_on:
          - api
        restart: unless-stopped
    cache:
        image: redis:3.2
        ports:
            - '${REDIS_PORT}:6379'
        restart: unless-stopped
    database:
        image: postgres:9.6
        ports:
            - '${POSTGRES_PORT}:5432'
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - PGDATA=/var/lib/postgresql/data/ezsetup
        volumes:
            - ./.pgdata:/var/lib/postgresql/data/ezsetup
            - ./api/database/migrations:/docker-entrypoint-initdb.d
        restart: unless-stopped
